"""
thumbnailer.py - Automated thumbnail generation for Video Auto-Poster.
Uses Gemini Imagen 4.0.
"""
import os
import logging
import time
from google import genai
import config

logger = logging.getLogger(__name__)

def generate_thumbnail(prompt: str, output_folder: str) -> str:
    """
    Generates a thumbnail image using Gemini Imagen 4.0 and saves it.
    Returns the path to the generated image.
    """
    if not config.GEMINI_API_KEY:
        logger.error("No GEMINI_API_KEY found for thumbnail generation.")
        return None

    client = genai.Client(api_key=config.GEMINI_API_KEY)
    
    # We'll use a standard filename
    output_path = os.path.join(output_folder, "thumbnail.png")
    
    logger.info(f"Generating thumbnail in {output_folder}...")
    
    try:
        # Using Imagen 4.0
        response = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
        )
        
        if response.generated_images:
            img_data = response.generated_images[0].image.data
            with open(output_path, "wb") as f:
                f.write(img_data)
            logger.info(f"Thumbnail saved to {output_path}")
            return output_path
        else:
            logger.warning("No images generated by Imagen.")
            return None
            
    except Exception as e:
        logger.error(f"Error generating thumbnail: {e}")
        # Secondary fallback
        try:
            logger.info("Retrying with experimental model...")
            response = client.models.generate_images(
                model='gemini-2.0-flash-exp-image-generation',
                prompt=prompt,
            )
            if response.generated_images:
                img_data = response.generated_images[0].image.data
                with open(output_path, "wb") as f:
                    f.write(img_data)
                return output_path
        except Exception as e2:
            logger.error(f"Experimental model also failed: {e2}")
            
    return None
